#!/bin/bash
echo -e "***欢迎使用 Deepin 龙芯版系统备份工具***\n"
echo -e "使用前请确认满足以下条件:\n1.当前电脑开机使用的是live系统(即用于安装系统的 系统安装光盘 或者 u盘 启动系统)\n2.需要备份的系统已经安装在当前电脑的硬盘上\n3.电脑额外插入一个用于存储备份数据的u盘、或者是移动硬盘(u盘可用空间最好大于5G,为防止存储空间不够大推荐使用移动硬盘)\n"

INPUT_DATA=''
    echo  "请选择是否继续[ Y/n ] ?"
    read -n 1  INPUT_DATA

case $INPUT_DATA in  Y|y|'' )
   ;;
    * )
    echo "您选择了退出备份,欢迎再次使用!"
    exit 0
   ;;
esac

[ -d /tmp/backup ] || mkdir -p /tmp/backup 



     livecd_sd_line=$( mount | grep "cdrom" | grep sd ) 
     livecd_sr_line=$( mount | grep "cdrom" | grep sr )
    if [ "$livecd_sd_line" == "" ] && [ "$livecd_sr_line" == "" ]
        then
        echo "请启动live系统,用于备份系统,制作live系统(即系统安装盘)请参看安装系统相关文档" && exit 0
        fi
    livecd_sd=${livecd_sd_line%% on*}

sds=$( find /dev -name sd*1 )
nsds=$( find /dev -name sd*1 | wc -l )
if [ $nsds != 3 ] && [ "$livecd_sd_line" != "" ]
    then
    echo -e "请确保只有且只有一个用于存放备份数据的存储设备!"
    exit 0
    elif [ $nsds != 2 ] && [ "$livecd_sr_line" != "" ] 
    then
    echo -e "请确保只有且只有一个用于存放备份数据的存储设备!"
    exit 0
   fi 

rootuuid=''
rootsd=''

for sd in $sds 
    do
    if [ $sd != "$livecd_sd" ]
    then
    tmpdir="/tmp/backup$sd"
         mkdir -p $tmpdir
         sudo mount $sd $tmpdir
        if [ -f $tmpdir/boot/grub.cfg ] 
            then
            rootuuidline=$( grep -r "UUID" $tmpdir/boot/grub.cfg )
            rootsd=$sd
            rootuuid=${rootuuidline##*root=}
            sync && sudo umount $tmpdir
            break
            fi
        sync && sudo umount $tmpdir
    fi
    done

store_sd=''

for sd in $sds
    do 
        if [ $sd != "$rootsd" ] && [ $sd != "$livecd_sd" ];then
        store_sd=$sd
        break
        fi
    done


sudo mount $rootuuid /tmp/backup$rootsd
[ -f /tmp/backup$rootsd/etc/fstab ] 

mkdir -p /tmp/backup$store_sd
sudo mount $store_sd /tmp/backup$store_sd
[ $? -ne 0 ] && echo -e  "存放备份数据的磁盘分区挂载失败,提示：\n请不要在备份还原操作前，打开文件管理器或者挂载存放数据的磁盘\n如果已经打开文件管>    理器或者挂载，请关闭文件管理器窗口，拔出存储设备，重新插入，再运行本命令\n" && exit 0

[ -d /tmp/backup$store_sd/deepin_system_backup_files ] || sudo mkdir -p -m 777 /tmp/backup$store_sd/deepin_system_backup_files
sudo rm -rf /tmp/backup$store_sd/deepin_system_backup_files/*
cp /tmp/backup$rootsd/etc/fstab  /tmp/backup$store_sd/deepin_system_backup_files/fstabinfo
uuids=$(grep -r "UUID" /tmp/backup$rootsd/etc/fstab | grep "/" | awk '{ print $1 }')

for uuid in $uuids
    do
    echo -e "开始备份分区uuid为 $uuid 的分区...\n"
    name=${uuid##*UID=}
    mkdir -p /tmp/backup/$name
    sudo mount $uuid /tmp/backup/$name
    sudo mksquashfs /tmp/backup/$name /tmp/backup$store_sd/deepin_system_backup_files/$name.squashfs
    sync && sudo umount /tmp/backup/$name
        done
echo "开始做善后处理请稍后..." && sync && sudo umount /tmp/backup$store_sd && sudo umount /tmp/backup$rootsd
echo -e "恭喜,您的系统已经备份到存储盘根目录的 deepin_system_backup_files 目录\n注意三点:\n1.请勿修改备份文件夹的位置以及文件夹名称\n2.请勿修改备份文件夹下的任何文件\n3.请勿在还原系统前，格式化你所备份的系统所在的硬盘，也不要对该硬盘执行新建或删除磁盘分区操作"
#end

